---
# Basic provisioning example
- name: Ansible test
  vars:
      aws_region: 
      aws_key_pair:
      aws_instance_type:
      aws_image_id:
      aws_subnet_id:
      aws_sec_group_name:
      instance_name:
      instance_count:
  hosts: localhost
  tasks:
    - name: launching AWS instance using Ansible
      ec2:
        #Set AWS Region
        region: '{{ aws_region }}'
        #Set key pair in AWS
        key_name: '{{ aws_key_pair }}'
        #Set instance size
        instance_type: '{{ aws_instance_type }}'
        #Update AWS Image ID (Region specific)
        image: '{{ aws_image_id }}'
        wait: yes
        count: '{{ instance_count }}'
        #Enter VPC Subnet ID
        vpc_subnet_id: '{{ aws_subnet_id }}'
        assign_public_ip: yes
        #Enter AWS Security Group Name
        group: '{{ aws_sec_group_name }}'
        #Add Tags as needed
        instance_tags:
          Name: '{{ instance_name }}'
          Creator: Ansible
      register: ec2_sdm
    - name: Add new instance to SDM's host group
      add_host:
        hostname: '{{ item.public_ip }}'
        groupname: launched-ec2-sdm
      with_items: '{{ ec2_sdm.instances }}'
    - name: Let's wait for SSH to come up. Usually that takes ~10 seconds
      local_action: wait_for 
        host={{ item.public_ip }} 
        port=22 
        state=started
      with_items: '{{ ec2_sdm.instances }}'
#Self Registered Example
- hosts: launched-ec2-sdm
  vars:
    username: 
  name: configuration play
  user: '{{ username }}'
  become: yes
  gather_facts: true
  tasks:
    #Update Path to script
    - script: scripts/sdm-sshadd.sh